baseURL = "/"
title = "新疆应急法规汇编"
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'

theme = "hugo-book"
# enableGitInfo = true

[params]
  BookTheme = 'auto'

  BookToC = false
  BookSection = 'docs'

  BookSearch = true
  BookComments = false
  BookFlatSection = true
  enableInlineShortcodes = true